#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

cd $PKG_BUILD

#cp -v $SYSROOT_PREFIX/usr/include/libusb-1.0/libusb.h ./src/
#cp -v $SYSROOT_PREFIX/usr/include/glib-2.0/glib.h ./src/
#cp -v $SYSROOT_PREFIX/usr/include/glib-2.0/glibconfig.h ./src/
#[ ! -d src/glib ] && mkdir ./src/glib
#cp -v $SYSROOT_PREFIX/usr/include/glib-2.0/glib/galloca.h ./src/glib/
#cp -v $SYSROOT_PREFIX/usr/include/glib-2.0/glib/gtypes.h ./src/glib/
#
#[ ! -d src/include ] && mkdir ./src/include
#cp -v $SYSROOT_PREFIX/usr/lib/glib-2.0/include/glibconfig.h ./src/include/

#FLAGSGLIBC="$CFLAGS -I$SYSROOT_PREFIX/usr/include -I$SYSROOT_PREFIX/usr/include/libusb-1.0"
#CFLAGS="$CFLAGS -I$SYSROOT_PREFIX/usr/include -I$SYSROOT_PREFIX/usr/include/libusb-1.0"
#LDFLAGS="$LDFLAGS -L$SYSROOT_PREFIX/lib -L$SYSROOT_PREFIX/usr/lib"
#export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${SYSROOT_PREFIX}/usr/include/libusb-1.0"
$MAKE xboxdrv

# do not build with LTO support
#  strip_lto





#./configure --prefix=/usr \
#            --arch=$TARGET_ARCH \
#            --cpu=$TARGET_CPU \
#            --cc=$TARGET_CC \
#            --enable-timeshift \
#            --disable-libav \
#            --disable-avahi \
#            --enable-bundle
#
#make

# compile capmt_ca.so library
#$CC -O -fbuiltin -fomit-frame-pointer -fPIC -shared -o capmt_ca.so src/extra/capmt_ca.c -ldl
